### ISSUE TITLE
[question] how to use installr to install not from CRAN

### ISSUE THREAD

**Issue by dselivanov** [r-hub/r-minimal#1]
Thanks for this great work. Is is possible to install from locations other than CRAN ? would be great if you could add examples.
Thanks in advance.

**Comment by gaborcsardi** [comment]
You can install from Github like this:
```
installr user/repo
```

It does not yet support all the nifty stuff from devtools/remotes, it would be easiest to add these after https://github.com/r-lib/remotes/issues/383 is implemented.

**Comment by dselivanov** [comment]
Thanks!
However still can't figure out how to refer branch or tag - is it possible? 
Also is there an easy way to install pkg from a local file (while resolving dependencies)?

**Comment by gaborcsardi** [comment]
No, not currently possible to install from a tag.

No way to install from a local pkg, either.

For these you can install the remotes package first, and then use `remotes::install_github()` or `remotes::install_deps()`.
