### ISSUE TITLE
How to set the version of an R package to be installed

### ISSUE THREAD

**Issue by DzimitryM** [r-hub/r-minimal#19]
I wonder if it is possible to specify the version of the R package to be installed in the docker? It would be nice to have this feature in order to be able to install not the latest version, e.g. _dplyr 0.8.4_.

**Comment by gaborcsardi** [comment]
This will be eventually solved by #4, but you can do it now by installing the remotes package first and then using that to install the rest:
```
installr remotes
R -q -e 'remotes::install_version("dplyr", "0.8.4")'
```

**Comment by DzimitryM** [comment]
Thank you for the response!
I would add that this approach with the library 'remotes' requires that dependencies should be available. Afterwards, in order to minimize the image size I had to remove them manually. In case of `dplyr` package I had to priorly install `g++` and then remove it along with its child dependencies. The corresponding dockerfile is:
```
FROM rhub/r-minimal
RUN installr remotes && \
    echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> ~/.Rprofile && \
    apk add g++ && \
    R -q -e 'remotes::install_version("dplyr", version = "0.8.4", build_vignettes = FALSE, build_opts = c("--no-multiarch", "--clean", "--no-docs", "--without-keep.source", "--no-data", "--no-help", "--no-demo", "--no-resave-data", "--no-manual", "--no-build-vignettes"))' && \
    apk del g++ libc-dev musl-dev gcc mpc1 mpfr3 libatomic libgomp isl gmp binutils
```
Resulting image is 180MB

**Comment by gaborcsardi** [comment]
If you want to remove the compilers automatically, you can try to call
```
installr -d
```
after the installation, it will remove them I believe, together with all dependencies, I think.
