### ISSUE TITLE
Not able to build earlier R versions

### ISSUE THREAD

**Issue by thiago4int** [r-hub/r-minimal#28]
I'm not allowed to pull r 4.0.1
Any suggestion?
Thank you very much

**Comment by gaborcsardi** [comment]
Seems like there is a problem on Docker Hub, e.g. this page does not work for me: https://hub.docker.com/r/rhub/r-minimal/tags?page=1&ordering=last_updated

Try pulling them from GitHub Packages:
https://github.com/r-hub/r-minimal/packages/92808?version=4.0.1

**Comment by thiago4int** [comment]
`docker pull docker.pkg.github.com/r-hub/r-minimal/r-minimal:4.0.1`

Error response from daemon: Head https://docker.pkg.github.com/v2/r-hub/r-minimal/r-minimal/manifests/4.0.1: no basic auth credentials

**Comment by thiago4int** [comment]
docker pull docker.pkg.github.com/r-hub/r-minimal/r-minimal:4.0.1
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=docker.pkg.github.com%2Fr-hub%2Fr-minimal%2Fr-minimal&tag=4.0.1: dial unix /var/run/docker.sock: connect: permission denied

**Comment by gaborcsardi** [comment]
You need to `docker login` with your github credentials, i think. 

The second error means that your Docker daemon is not running out your do not have access to it.

**Comment by gaborcsardi** [comment]
Docker Hub is back online and 
```
docker pull rhub/r-minimal:4.0.1
```
works again.
