### ISSUE TITLE
no basic auth credentials - 4.0.1 patched and 4.0.3 patched

### ISSUE THREAD

**Issue by thiago4int** [r-hub/r-minimal#29]
Hi team, can someone help me out on this issue?

`Sending build context to Docker daemon   2.56kB
Step 1/8 : FROM docker.pkg.github.com/r-hub/r-minimal/r-minimal:4.0.3-patched as builder
Head https://docker.pkg.github.com/v2/r-hub/r-minimal/r-minimal/manifests/4.0.3-patched: no basic auth credentials
ERROR
`

**Comment by gaborcsardi** [comment]
You need to `docker login` with your github credentials, i think.
