### ISSUE TITLE
Host images on Github

### ISSUE THREAD

**Issue by bransonf** [r-hub/r-minimal#3]
Any plans to host these images on Github's package repository in addition to Docker hub?

All you have to do is tag the image with:
```
docker.pkg.github.com/r-hub/r-minimal/<image name>:<version>
```

and push.

Thanks for the consideration.

**Comment by gaborcsardi** [comment]
What would be the advantage of having them on GitHub as well?

**Comment by bransonf** [comment]
It's free, easy enough and redundancy is always a good thing. More particularly, I'd like to take advantage of Github's actions to automate builds with these images. It's simpler to only have to maintain my Github credentials and use their CDN than having to integrate/manage credentials for Docker hub as well.

If this isn't something you'd like to maintain, I understand and I can just host my own images. Thanks again for these images.

**Comment by gaborcsardi** [comment]
OK, I'll push to GH as well. I want to use them with GH Actions as well, actually, so this is good. Let me build a new image, and then I'll push it.

**Comment by gaborcsardi** [comment]
Btw. there is probably a way to auto-push new versions to GH, I suppose?

**Comment by bransonf** [comment]
Yes, I believe you can trigger a build on push/pr to master. You could also automate the push to Docker hub I believe.

[See this documentation](https://github.com/marketplace/actions/build-tag-publish-docker)

**Comment by gaborcsardi** [comment]
Yes, Docker Hub is linked: https://hub.docker.com/repository/docker/rhub/r-minimal I'll set up an Action to push to GH. Thanks!

**Comment by bransonf** [comment]
Thank you! I discovered this at just the right time. I'm working on making some smaller images for spatial data work in R because the leading alternative (rocker/geospatial) is over 4GB.

**Comment by gaborcsardi** [comment]
I am afraid that the spatial packages will be big, but yeah, you can probably shave it a bit. 

Btw. it is here: https://github.com/r-hub/r-minimal/packages/92808
