### ISSUE TITLE
JPEG and PNG dependencies

### ISSUE THREAD

**Issue by thiago4int** [r-hub/r-minimal#30]
How can I install jpeg and PNG dependent packages or even ignore those dependencies?

Anomalize is being really tricky.

Thank you folks!

**Comment by gaborcsardi** [comment]
```
installr -d -t libjpeg-turbo-dev -a libjpeg-turbo jpeg
installr -d -t libpng-dev -a libpng png
```

This seems to work:

```
installr -d -t "curl-dev gfortran" anomalize
```

**Comment by thiago4int** [comment]
That works! Thank you very much!
Is there any way to define a specific version of this package?
Btw is there any way to downgrade any package to a specific version after installation?

**Comment by gaborcsardi** [comment]
Not with `installr`, but you can run 

```
installr -c
``` 

to install the compilers and then use `install.packages()` or any other way you want to install R packages, e.g. install remotes and use `remotes::install_version()`.
