### ISSUE TITLE
Feature Request: Add example for pagedown

### ISSUE THREAD

**Issue by datalorax** [r-hub/r-minimal#34]
Thanks for much for this resource. The size of the resulting docker files is amazing compared to what I was working with before.

I wanted to ask if it would be possible to create an example with pagedown that includes the parts related to chrome for pdf rendering? 

Thanks for considering.

**Comment by gaborcsardi** [comment]
pagedown is really cool! The image is not that small, since it needs pandoc and chromium. Let me know if you have any issues.

**Comment by datalorax** [comment]
Wonderful! Still much better than what I was working with before. Thank you so much!

**Comment by datalorax** [comment]
Hi Gábor, I apologize if this should be obvious. I see in the README that these images do not have JPEG, PNG, TIFF, or Cairo support. It seems that makes [html_paged](https://github.com/rstudio/pagedown/blob/main/inst/rmarkdown/templates/html-paged/skeleton/skeleton.Rmd) fail. For example, if I save this to `ex.Rmd` (omitting the random text from the template)

```r
---
title: "A Multi-page HTML Document"
author: "Yihui Xie and Romain Lesur"
date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    toc: true
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: true
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

​​​​```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE)
​​​​```

# Introduction

This is an example of a multi-page HTML document. See https://pagedown.rbind.io for the full documentation. 
```

And then run `cat ex.Rmd | docker run -i pagedown-ex pagedown.sh > ex.pdf` where `pagedown-ex` is my built docker image, I get

```
Quitting from lines 15-16 (card.Rmd) 
Error in (function (filename = if (onefile) "Rplots.svg" else "Rplot%03d.svg",  : 
  svg: Cairo-based devices are not available for this platform
Calls: <Anonymous> ... block_exec -> eng_r -> chunk_device -> do.call -> <Anonymous>
Execution halted
```

Is there a way around this? Totally okay if the answer is "no", I just want to make sure before I pursue other options.

**Comment by gaborcsardi** [comment]
Can you try with the svg device of the svglite package? Something like

````
```{r dev = "svglite"}
...
```
````

You need to install svglite as well, of course.

**Comment by datalorax** [comment]
Aha! That worked. Thanks again!

**Comment by gaborcsardi** [comment]
I'll add that to README.

**Comment by datalorax** [comment]
Thanks. One last question. I was able to get it to run without actually installing **svglite** by just specifying it as you have above. But I need it installed for my actual application. I've tried *really* hard to get it installed but I am a bit out of my depth here. I'm having issues with the **systemfonts** dependency.  I'm getting the following error


>Configuration failed to find the fontconfig freetype2 library. Try installing:
> * deb: libfontconfig1-dev (Debian, Ubuntu, etc)
 >* rpm: fontconfig-devel (Fedora, EPEL)
 >* csw: fontconfig_dev (Solaris)
 >* brew: freetype (OSX)
 
I've tried running

```
RUN apk add --repository http://nl.alpinelinux.org/alpine/v3.11/main \
  fontconfig-dev=2.13.1-r2
```

And exporting the path with 

```
RUN export PKG_CONFIG_PATH=/usr/lib/pkgconfig
```

But to no avail. Any chance you could help me get **svglite** installed? Sorry to keep bugging you with this.

**Comment by gaborcsardi** [comment]
This works for me:
```
installr -d -a fontconfig -t fontconfig-dev svglite
```

**Comment by datalorax** [comment]
🙌 Thank you! That is embarrassingly easy.
