### ISSUE TITLE
Build arm64 containers as well

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/r-minimal#36]
Using buildx action at https://github.com/docker/setup-buildx-action

**Comment by jeroen** [comment]
I tried some of this with the r-svn mirror, but qemu is soooo slow https://github.com/r-devel/r-svn/runs/3618418633?check_suite_focus=true

**Comment by gaborcsardi** [comment]
Just the building time is not so bad, it built amd64 on the M1 in about 25 minutes.

**Comment by gaborcsardi** [comment]
OK, managed to push it to both docker hub and GH packages: 
https://hub.docker.com/repository/docker/rhub/r-minimal/tags?page=1&ordering=last_updated
https://github.com/r-hub/r-minimal/pkgs/container/r-minimal%2Fr-minimal/10640414?tag=latest

Just need to automate it now...

**Comment by gaborcsardi** [comment]
IDK what is going on but the arm64 build gets a network failure when downloading the R sources. It can download other stuff before that so networking should be ok.

It works fine locally, both on arm64 and amd64. I'll give this up for now.

**Comment by gaborcsardi** [comment]
Possibly the issue is that I am already using a container action, so now I am trying to use buildx within a container.

**Comment by gaborcsardi** [comment]
I installed proper `wget` on the image, and now it went past that but still failed with 
```
#14 6.405 checking whether we are cross compiling... configure: error: in `/root/R-devel':
#14 7.563 configure: error: cannot run C compiled programs.
#14 7.563 If you meant to cross compile, use `--host'.
#14 7.563 See `config.log' for more details
```

https://github.com/r-hub/r-minimal/runs/4285433386?check_suite_focus=true

So this seems like a pain as a container action.

**Comment by mcanouil** [comment]
If it helps, [rocker-org/rocker-versioned2](https://github.com/rocker-org/rocker-versioned2) is using a github action workflow ([core.yml](https://github.com/rocker-org/rocker-versioned2/blob/master/.github/workflows/core.yml)) to build multiple Docker images with buildx and a json file.
I built a "simpler" workflow based on their repository => https://github.com/mcanouil/docker-versioned-test/

**Comment by eitsupi** [comment]
I introduced arm64 using `docker buildx` in https://github.com/rocker-org/rocker-versioned2.
In https://github.com/rocker-org/rocker-versioned2, it was not suitable because there are too many Dockerfiles to build, but using https://github.com/docker/build-push-action, we can easily build multi-arch images. (e.g. https://github.com/rocker-org/rocker-versioned2/pull/179)

I had thought earlier that it might be possible to implement automatic R version updates and multi-architecture builds in this project as well, but it looked difficult to fix because it was building by its own actions.
If you can consider switching to the docker/build-push-action, I would be honored to help.

**Comment by gaborcsardi** [comment]
There is some progress on this now, and `arm64` containers are available for all supported R versions. However, there are no pak binaries for arm64 yet, so `installr` does not work, and you'll need to use other ways to install packages.

**Comment by gaborcsardi** [comment]
Unfortunately it seems that the arm64 containers do not work well on amd64, which is an issue because you can't run them on GHA. We get when building pak on GHA using these containers:
```
#9 [linux/arm64  4/17] RUN PAK_BUNDLE=false R CMD INSTALL .
#9 0.871 INSTALL: applet not found
#9 ERROR: process "/bin/sh -c PAK_BUNDLE=false R CMD INSTALL ." did not complete successfully: exit code: 127
```

This could be a bug in busybox, Alpine or qemu. Or just some unfortunate interplay. 

Stock Alpine and its R package also does not work cross-platform, and fails the same way on my arm64 laptop when trying to run x86_64 Docker images.

One way to fix it is to change the shell to bash instead of busybox. This makes the images slightly larger, which is probably OK. IDK if it has any more consequences.

**Comment by gaborcsardi** [comment]
OK, arm64 images are now generally available, and work the same way, i.e. `installr` also works out of the box. I'll update the README.
