### ISSUE TITLE
installr returns exit code 0 even when package fails to install

### ISSUE THREAD

**Issue by program--** [r-hub/r-minimal#38]
Hi, I use this container extensively as a base for a bunch of others (thank you so much for it!) -- one issue that seems to come up though is on build, when a package fails to install with `installr`, it will still return an exit code of 0. In the context of CI/CD pipelines, this ends up with a false success a lot of the time :sweat_smile:.

Since the `Rscript` call returns a non-zero exit code on installation failure, a quick (and potentially naive) solution would be to append `|| exit 1` here:
https://github.com/r-hub/r-minimal/blob/d61fa1db104ab1d6d88dd5be82d836eaef69cc66/installr#L71
such that the line becomes:
```bash
Rscript -e 'pak::pkg_install(commandArgs(TRUE))' "$@" || exit 1
```

I've tested it quickly by building a container with only the commands, which seems to work as expected:
```Dockerfile
# Will install successfully
RUN installr -d dplyr

# Will fail without GDAL, etc.
RUN installr -d sf
```

I didn't see any discussion on this, but if it's just me having this issue then feel free to close this!

**Comment by gaborcsardi** [comment]
Yeah, that is good. But I am wondering if we should just do `set -e` to exit on any error.

**Comment by program--** [comment]
I agree, that's a better handler for failure than what I suggested. :smile:

**Comment by gaborcsardi** [comment]
OK, do you want to submit a PR? (No pressure.)
