### ISSUE TITLE
Build Error with Rserve

### ISSUE THREAD

**Issue by DavZim** [r-hub/r-minimal#41]
When installing `Rserve` on `r-minimal` the install fails as the shared library of R is not found.

# Error Output

```
#> Failed to build source package 'Rserve', stdout + stderr:
#>  * installing *source* package ‘Rserve’ ...
#>  ** package ‘Rserve’ successfully unpacked and MD5 sums checked
#>  staged installation is only possible with locking
#>  ** using non-staged installation
#>  checking whether to compile the server... yes
#>  configure: error: R was configured without --enable-R-shlib or --enable-R-static-lib
#> 
#>  *** Rserve requires R (shared or static) library.                       ***
#>  *** Please install R library or compile R with either --enable-R-shlib  ***
#>  *** or --enable-R-static-lib support                                    ***
#> 
#>   Alternatively use --without-server if you wish to build only Rserve client.
#> 
#> 
#>  ERROR: configuration failed for package ‘Rserve’
```

# Steps to Reproduce

Using the following Dockerfile
```
FROM rhub/r-minimal:4.1.2

RUN installr -d Rserve
```

and then building it with `docker build -t rserve-tester .` results in the above error.

# Comments

This is related to [`RServe`'s #110](https://github.com/s-u/Rserve/issues/110).

The error is probably a result of [`Dockerfile#L8`](https://github.com/r-hub/r-minimal/blob/master/Dockerfile#L8) `ENV _R_SHLIB_STRIP_=true` but I am not sure as I have little experience building R from source and its related build flags.

**Comment by gaborcsardi** [comment]
> The error is probably a result of [`Dockerfile#L8`](https://github.com/r-hub/r-minimal/blob/master/Dockerfile#L8) `ENV _R_SHLIB_STRIP_=true`

Why do you think so? AFAICT Rserve still does not build with Alpine's stock R package, either.

**Comment by gaborcsardi** [comment]
Yes, Rserve will not work because we don't use `--enable-R-shlib` or `--enable-R-static-lib`.

**Comment by gaborcsardi** [comment]
I can check if the image gets bigger if we use one of them.

**Comment by gaborcsardi** [comment]
Btw. re https://github.com/s-u/Rserve/issues/110 I managed to compile Rserve with the stock Alpine R, just needed some Alpine packages: make, R, R-dev, musl-dev, gcc, bash. bash might not be needed, actually.

**Comment by gaborcsardi** [comment]
Seems like a shared R lib barely increases the size, so we can try that.

**Comment by gaborcsardi** [comment]
Once these new images are built it should work:
https://github.com/r-hub/r-minimal/actions/runs/1725096437
It is quite slow, it will take about 3 hours.

**Comment by DavZim** [comment]
Wonderful, thank you so much for looking into it. I'll test it out tomorrow and let you know!

**Comment by DavZim** [comment]
Works like a charm.
