### ISSUE TITLE
Alpine package pandoc is currently not available 

### ISSUE THREAD

**Issue by KevCaz** [r-hub/r-minimal#43]
HI @gaborcsardi,

Looks like the package is not currently available (see https://gitlab.alpinelinux.org/alpine/aports/-/issues/13195) so currently one can install rmarkdown with `RUN installr -d rmarkdown` but `rmarkdown::pandoc_available()` will return `FALSE`.

Workaround:

````sh
FROM rhub/r-minimal

# adapted from https://community.rstudio.com/t/alpine-based-rmarkdown/116348
RUN wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-linux-amd64.tar.gz -O pandoc.tar.gz \
    && tar xzf pandoc.tar.gz \
    && mv pandoc-2.17.1.1/bin/* /usr/local/bin/ \
    && rm -rf pandoc*

RUN installr -d rmarkdown 

CMD ["R"]
````

Maybe there is another way I am not aware of, maybe I missed a piece of info.... Anyway, **thanks a lot** for your work on this, got a 2.GB image shrunk to 800MB.

**Comment by gaborcsardi** [comment]
There is an example in `examples/rmarkdown`, which does basically the same.
