### ISSUE TITLE
ERROR: compilation failed for package ‘Matrix’

### ISSUE THREAD

**Issue by greenjune-ship-it** [r-hub/r-minimal#45]
Dear Team,

I faced an installation issue with **Matrix** R package inside the container. I tried to install it with the **installr** tool using the following command:
 `system('installr -c Matrix')`
I received the compilation errors, I assume the main cause in these two gcc packages:
```
cannot find -lgfortran
cannot find -lquadmath
```

I've attached the full installation log with errors as well:
[Matrix-installation-log.txt](https://github.com/r-hub/r-minimal/files/8462350/Matrix-installation-log.txt)

I solved the issue with manual installation of these packages:
`system('apk add gfortran libqaudmath')`
I'm not sure if **installr** tool should automatically detect such system dependencies for package installation, but I report my issue just in case it might be useful for other users!

P.S. I've recently discovered your project and really excited how easy it became to work with R with r-minimal!

Thank you

**Comment by gaborcsardi** [comment]
> I'm not sure if installr tool should automatically detect such system dependencies for package installation

No, installr does not automatically install system dependencies currently. It can add system dependencies, though. This works for me:

```
installr -d -t gfortran Matrix
```

This temporarily installs the C/C++ compiler plus gfortran, and then removes them after the installation of the R packages, so the Docker image is still kept small.
