### ISSUE TITLE
rJava package install for xlsx

### ISSUE THREAD

**Issue by cmccabe0728** [r-hub/r-minimal#48]
Trying to build the xlsx R package, but the package dependencies don't seem to install. I tried adding Java to path and using apt-get and using a multistage build, but I still get the same. Thank you.

    FROM rhub/r-minimal:4.1.3

    RUN  installr rJava xlsxjars

    → Will install 2 packages.
    → Will download 2 CRAN packages (10.52 MB).
    + rJava      1.0-6 [bld][cmp][dl] (1.05 MB)
    + xlsxjars   0.6.1 [bld][dl] (9.48 MB)
     Getting 2 pkgs (10.52 MB)
     Got rJava 1.0-6 (source) (1.05 MB)
     Got xlsxjars 0.6.1 (source) (9.48 MB)
     Building rJava 1.0-6
     Failed to build rJava 1.0-6
    Error:
    ! error in pak subprocess
    Caused by error in `stop_task_build(state, worker)`:
    ! Failed to build source package 'rJava'

**Comment by gaborcsardi** [comment]
Why not install the Alpine java package? `apk add openjdk11` works for me....

**Comment by cmccabe0728** [comment]
The xlsx package is looking for rJava and xlsxjars and will not install with just java added.... I also tried.... Thank you :).

            export JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre \
     && export PATH=$PATH:$JAVA_HOME/bin \
     && R CMD javareconf -e

    /usr/local/lib/R/bin/javareconf: line 106: openjdk8-jre: command not found


    *** Java interpreter doesn't work properly.

**Comment by gaborcsardi** [comment]
Oh, actually, jus realized that r-minimal does not have Java support, sorry, see https://github.com/r-hub/r-minimal#limitations

**Comment by cmccabe0728** [comment]
Thank you very much :)
