### ISSUE TITLE
use of the "patched" tag

### ISSUE THREAD

**Issue by username-is-already-taken2** [r-hub/r-minimal#49]
Hi there

I can't seem to find a reference in the readmes that explain what are the images tagged with the word `patched` could one help me understand what has been patched?  happy to PR an updated readme or something to pay it forward.

Thanks

Gary

**Comment by gaborcsardi** [comment]
See the docs here: https://cran.r-project.org/sources.html

**Comment by gaborcsardi** [comment]
It is basically a snapshot of the current release branch.
