### ISSUE TITLE
Update Alpine Version?

### ISSUE THREAD

**Issue by Westat-Transportation** [r-hub/r-minimal#55]
First of all, this project is great.  Been looking for a way to use Alpine as a base for R containers for years and have been able to use this with minimal fuss.

My issue if with the version of Alpine in the published images in Docker Hub.  It seems to be a bit behind (3.14) and that is causing it to fail vuln scans in our container environment.  I also see versions of R referenced in DockerHub that are newer than what's in this repo.

So, I am not sure what would be the process for addressing this since you are likely building the containers from some other repo.  Would a PR updating the base Alpine img tag be something you'd be willing to review?  I tested locally and was able to build the img with Alpine 3.16.

**Comment by gaborcsardi** [comment]
Sure, a pr is a welcome. Thanks!

**Comment by gaborcsardi** [comment]
Closed by #56.
