### ISSUE TITLE
libcurl >= 7.28.0 library and headers are required with support for https

### ISSUE THREAD

**Issue by aabusharekh** [r-hub/r-minimal#57]
Building master branch on Ubuntu 22.04.2 LTS

#0 10.18 checking for pcre2_compile_8 in -lpcre2-8... yes
#0 10.20 checking if PCRE2 has Unicode support... yes
#0 10.26 checking whether PCRE support suffices... yes
#0 10.26 checking for curl-config... /usr/bin/curl-config
#0 10.26 checking libcurl version ... 8.0.1
#0 10.26 checking for curl/curl.h... yes
#0 10.31 checking if libcurl is version 7 and >= 7.28.0... no
#0 10.36 configure: error: libcurl >= 7.28.0 library and headers are required with support for https
------
Dockerfile:43
--------------------
  42 |     
  43 | >>> RUN cd R-${R_VERSION} &&                                                 \
  44 | >>>     . FLAGS &&                                                           \
  45 | >>>     CXXFLAGS=-D__MUSL__  ./configure                                     \
  46 | >>>         --with-recommended-packages=no                                   \
  47 | >>>         --with-readline=yes --with-x=no --enable-java=no                 \
  48 | >>>         --enable-R-shlib                                                 \
  49 | >>>         --disable-openmp --with-internal-tzcode
  50 |     RUN cd R-${R_VERSION} && make -j 4
--------------------
ERROR: failed to solve: process "/bin/sh -c cd R-${R_VERSION} &&                                                     . FLAGS &&                                                         
      CXXFLAGS=-D__MUSL__  ./configure                                             --with-recommended-packages=no                                           --with-readline=yes --with-x
=no --enable-java=no                         --enable-R-shlib                                                         --disable-openmp --with-internal-tzcode" did not complete successfully: exit code: 1

**Comment by gaborcsardi** [comment]
This is not the place to report issues about R, that is at https://bugs.r-project.org/

Did you install libcurl? Also, you don't need to compile R for yourself, try installing rig (see https://github.com/r-lib/rig#the-r-installation-manager) and then call
```
rig add release
```
to install the latest R release.
