### ISSUE TITLE
Feature request: installr support for renv

### ISSUE THREAD

**Issue by JosiahParry** [r-hub/r-minimal#58]
I think a huge win for installr would be a one line command to install dependencies directly from an `renv.lock` file. 

Then a `Dockerfile` could look something like 

```dockerfile
FROM r-hub/r-minimal
COPY renv.lock
RUN installr -f renv.lock
CMD ["Rscript", "myscript.R"]
```

**Comment by gaborcsardi** [comment]
Can you just call `renv::restore()` to install all packages instead?

**Comment by gaborcsardi** [comment]
Haven't actually tried this, but indeed this seems simple if you copy the project to the `Dockerfile`.
