### ISSUE TITLE
trouble with install {arrow}

### ISSUE THREAD

**Issue by xiaodaigh** [r-hub/r-minimal#7]
I have some trouble installing {arrow} which in turn is caused by {rlang}

here my the the Dockerfile

```docker
FROM rhub/r-minimal
RUN installr -d -t libparquet-dev arrow
```

```r
/bin/sh: gcc: not found
make: *** [/usr/local/lib/R/etc/Makeconf:168: capture.o] Error 127
ERROR: compilation failed for package ‘rlang’
```

**Comment by gaborcsardi** [comment]
This is what I get:

```
~ # installr -d -tlibparquet-dev arrow

--------------------------------------
Temporarily adding libparquet-dev gcc musl-dev g++
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  libparquet-dev (missing):
    required by: world[libparquet-dev]

--------------------------------------
Removing libparquet-dev gcc musl-dev g++

--------------------------------------
Cleaning up cache
~ #
```

**Comment by gaborcsardi** [comment]
```
~ # apk search parquet
~ #
```

so apparently, there is no parquet in the base Alpine system.

**Comment by gaborcsardi** [comment]
Seems like you'll need to build arrow, which is not quite ideal: https://gist.github.com/bskaggs/fc3c8d0d553be54e2645616236fdc8c6

**Comment by xiaodaigh** [comment]
It doesn't work as jemalloc is not longer available

**Comment by xiaodaigh** [comment]
> Seems like you'll need to build arrow, which is not quite ideal: https://gist.github.com/bskaggs/fc3c8d0d553be54e2645616236fdc8c6

Those are instructions for Python. I will see if it works for R as well.

**Comment by gaborcsardi** [comment]
> I meant the part that builds the arrow library:

https://gist.github.com/bskaggs/fc3c8d0d553be54e2645616236fdc8c6#file-dockerfile-L25-L42

**Comment by gaborcsardi** [comment]
I added a note to the `README` about this. Please comment here if you have any news about compiling arrow on ALpine.

**Comment by gaborcsardi** [comment]
quite late, but arrow works now, see the example in `examples/arrow`.
