### ISSUE TITLE
R arrow example - enable S3 support

### ISSUE THREAD

**Issue by agmeiner-bhs** [r-hub/r-minimal#84]
Hi, 
thanks for the example installing arrow in alpine. 
To check the capabilities of the installed package, you can use arrow_info() and see, that s3-support ist OFF. 
[Installing on Linux](https://arrow.apache.org/docs/r/articles/install.html) describes, that s3-support would be turned on during build, if system dependencies

CURL: install libcurl-devel (rpm) or libcurl4-openssl-dev (deb)
OpenSSL >= 1.0.2: install openssl-devel (rpm) or libssl-dev (deb)

are found. 
The extention of the example 

```
RUN mkdir -p ~/.R && echo "LDFLAGS+=-fPIC" >> ~/.R/Makevars

RUN installr -d \
    -t "make cmake linux-headers" \
    -a "openssl openssl-dev curl-dev" arrow

RUN R -q -e 'library(arrow)'
```
was not successful in my case. 
* What is neccessary to add S3 support?
* Can buildtime be reduced by using [Apache Arrow Alpine package](https://pkgs.alpinelinux.org/package/edge/community/armhf/apache-arrow)

**Comment by gaborcsardi** [comment]
Maybe arrow does not find the system requirements?

**Comment by agmeiner-bhs** [comment]
Thanks! That worked

```
ENV ARROW_S3=ON

RUN mkdir -p ~/.R && echo "LDFLAGS+=-fPIC" >> ~/.R/Makevars
RUN installr -d \
    -t "make cmake linux-headers" \
    -a "openssl openssl-dev curl-dev" arrow
RUN R -q -e 'library(arrow)'
```

**Comment by gaborcsardi** [comment]
Cool, do you want to add a note to the example that points to your comment with the solution?

**Comment by agmeiner-bhs** [comment]
Hi, 

after some time I have to come back to this topic. 
I can't reproduce my result with the code above. Does anybody confirm this with all the changes on the image made since March?

**Comment by gaborcsardi** [comment]
The example now uses libarrow from Alpine which was not built with S3 support it seems:
```
d8d9ce40e19a:~# apk list --installed | grep arrow
apache-arrow-14.0.1-r3 aarch64 {apache-arrow} (Apache-2.0) [installed]
libarrow-14.0.1-r3 aarch64 {apache-arrow} (Apache-2.0) [installed]
libarrow_acero-14.0.1-r3 aarch64 {apache-arrow} (Apache-2.0) [installed]
libarrow_dataset-14.0.1-r3 aarch64 {apache-arrow} (Apache-2.0) [installed]
libparquet-14.0.1-r3 aarch64 {apache-arrow} (Apache-2.0) [installed]
```

```
d8d9ce40e19a:~# R -q -e 'arrow::arrow_info()' | grep s3
s3        FALSE
```

We can have another example that builds arrow from source (I assume that's still possible), and turns on S3 support. Do you want to submit a PR? (No pressure!)

**Comment by agmeiner-bhs** [comment]
Hi Gabor, sorry, I don't have a solution yet. When I do, I will definitely submit a PR...

**Comment by gaborcsardi** [comment]
So S3 support is off in libarrow on Alpine. I tried to rebuild the Alpine package with S3, but the build fails. 

If I install the aws sdk packages and try to build the R package from source, without Alpine arrow, that fails as well, for all the R package versions I tried (~5). So this does not seem easy. 

This was all on aarch64, it is entirely possible that x86_64 is better.

**Comment by agmeiner-bhs** [comment]
Hi Gabor, is it possible to use a newer or older version and it works again? Or is it a general problem somewhere?

**Comment by gaborcsardi** [comment]
If the `Dockerfile` in https://github.com/r-hub/r-minimal/issues/84#issuecomment-2007076495 worked for you, then you could try a daily R-devel build (https://github.com/r-hub/r-minimal#daily-r-devel-builds) from that day, with the arrow R package version that was current that day.

**Comment by gaborcsardi** [comment]
I am trying this one now, both on `aarch64` and `x86_64`:

```Dockerfile
FROM ghcr.io/r-hub/r-minimal/r-minimal:2024-03-19

ENV ARROW_S3=ON

RUN mkdir -p ~/.R && echo "LDFLAGS+=-fPIC" >> ~/.R/Makevars
RUN installr -d \
    -t "make cmake linux-headers" \
    -a "openssl openssl-dev curl-dev" arrow@15.0.1
RUN R -q -e 'library(arrow)'
```

**Comment by gaborcsardi** [comment]
OK, this works for both aarch64 and x86_64, although I didn't actually try to use it to connect to S3, but arrow claims to have S3 support. I'll it as an example.

**Comment by agmeiner-bhs** [comment]
Thanks for your help, proofs again that I should work as reproducible as possible for my work.
