### ISSUE TITLE
data.table does not detect openmp, while install appears fine

### ISSUE THREAD

**Issue by lpagie** [r-hub/r-minimal#87]
I installed data.table in a fresh r-minimal image. When I load the library I get a message stating openMP support is not detected.  
I opened an issue with the developers of data.table, but maybe this is a better place?  

https://github.com/Rdatatable/data.table/issues/6092

The data.table dev's helped me with an alternative smallish image (still ~600Mb) in which data.table works fine.  
Can anybody checkout the (now closed) issue on the data.table repos and tell me whether this place is better to solve the openmp/data.table issue?

thx

**Comment by gaborcsardi** [comment]
Install openmp and configure R or data table to use it. It should work fine. If you run into trouble, please open an issue with a Dockerfile that reproduces your problem.

**Comment by gaborcsardi** [comment]
Here is an example `Dockerfile`:
```
FROM ghcr.io/r-hub/r-minimal/r-minimal

RUN echo -e 'PKG_CFLAGS+=-fopenmp\nPKG_LIBS+=-fopenmp\n' >> /tmp/Makevars && \
    R_MAKEVARS_USER=/tmp/Makevars \
    installr -a "libgomp zlib" -t "openmp-dev zlib-dev" -d data.table && \
    rm /tmp/Makevars

RUN R -q -e 'data.table::getDTthreads()'

RUN ldd /usr/local/lib/R/library/data.table/libs/data_table.so 2> /dev/null || true
```

It seems to use 4 threads, links to libgomp and libz, and it is about 40MB on my arm64 machine.

```
...
#6 [3/4] RUN R -q -e 'data.table::getDTthreads()'
#6 0.467 > data.table::getDTthreads()
#6 0.541 [1] 4
#6 0.541 >
...
#7 [4/4] RUN ldd /usr/local/lib/R/library/data.table/libs/data_table.so 2> /dev/null || true
#7 0.091 	/lib/ld-musl-aarch64.so.1 (0xffffbf013000)
#7 0.091 	libz.so.1 => /lib/libz.so.1 (0xffffbef39000)
#7 0.091 	libgomp.so.1 => /usr/lib/libgomp.so.1 (0xffffbeeea000)
#7 0.091 	libc.musl-aarch64.so.1 => /lib/ld-musl-aarch64.so.1 (0xffffbf013000)
...
```

```
❯ docker inspect sha256:4cde39cc3c764160f9251e6bbdb706791749fbeca0a0a4f5ae3f0df2035b1aa0 | grep Size
        "Size": 40294639,
```

**Comment by gaborcsardi** [comment]
I'll add this as an example, it is more interesting than the current plain one...

**Comment by lpagie** [comment]
[Tried your suggestions](https://github.com/Rdatatable/data.table/issues/6092#issuecomment-2063340633) and works like a charm

Thanks!
I'm closing this issue.
