### ISSUE TITLE
Change for env

### ISSUE THREAD

**Issue by meztez** [r-hub/r-minimal#93]
https://github.com/r-hub/r-minimal/blob/92b6130d313f76e13df3b81372a064aa53831bdd/examples/xgboost/Dockerfile#L4

Instead?
```
ENV CXX_DEFS='-DDMLC_LOG_STACK_TRACE=0 -DDMLC_USE_FOPEN64=0'
```

**Comment by gaborcsardi** [comment]
Why? Is xgboost picking this up, or how does it work?

**Comment by meztez** [comment]
https://github.com/wch/r-source/blob/4a5e54e99fa50a9daa12e8d35b9b6b1ab40bf63a/etc/Makeconf.in#L180

R picks them up for C++ compiltation

**Comment by meztez** [comment]
Seems to be temporary https://github.com/wch/r-source/commit/f3b150a8d33ab11da73bb08c617b07dbb8212552

Not sure if they are going to keep it in

**Comment by gaborcsardi** [comment]
I don't know if it is temporary, but it surely does not work for older R versions.
